GET http://localhost:8000


###
POST http://localhost:8000/users/save
Content-Type: application/json

{
  "name": "Vijay Chrome",
  "deviceToken": "<Token>"
}

###
POST http://localhost:8000/users/notify
Content-Type: application/json

{
  "name": "Vijay Chrome"
}
